


# Oracle settings
spring:
  devtools:
    livereload:
      enabled: true
      
  jpa:
    database-platform : org.hibernate.dialect.MySQLDialect
    show-sql: true
#    hibernate:
#      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/techm
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver


    
# properties for Security     
server:
  port: 2020
  ssl:
     client-auth: need
     enabled: true
     key-password: s3cr3t
     key-store: classpath:server.jks
     key-store-password: s3cr3t
#     protocol: TLSv1.2
     trust-store: classpath:server.jks
     trust-store-password: s3cr3t
     


#Logging
logging:
  file: D:\OneViewForCustomer\workspace\SamplePOC\poc_log.log
  level:
#    org:
#      springframework:
#        security: DEBUG
    hibernate: DEBUG
    
  path: concretepage/logs
  pattern:
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'  